/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Attempts {
  candidateId: string;
  createdAt: Date | null;
  hasEnded: Generated<number>;
  id: string;
  order: number;
  secondsSpent: Generated<number>;
  status: Generated<"COMPLETED" | "GRADED" | "IN_PROGRESS">;
  TestId: string | null;
  updatedAt: Date | null;
}

export interface AttemptsAnswerLAQuestions {
  answer: string;
  attemptAnswerQuestionId: string;
}

export interface AttemptsAnswerMCQQuestions {
  attemptAnswerQuestionId: string;
  chosenOption: number;
}

export interface AttemptsAnswerQuestions {
  AttemptId: string | null;
  createdAt: Date | null;
  id: string;
  pointsReceived: number | null;
  QuestionId: number | null;
  updatedAt: Date | null;
}

export interface ExamParticipants {
  candidateId: string;
  createdAt: Date | null;
  id: string;
  testId: string;
  updatedAt: Date | null;
}

export interface ExamTests {
  closeDate: Date;
  createdAt: Date | null;
  isAllowedToSeeOtherResults: Generated<number>;
  isAnswerVisible: Generated<number>;
  numberOfAttemptsAllowed: Generated<number>;
  openDate: Date;
  password: string | null;
  roomId: string;
  testId: string;
  updatedAt: Date | null;
}

export interface Feedbacks {
  comment: string;
  createdAt: Date | null;
  id: string;
  problems: Json;
  rating: number;
  TestId: string | null;
  updatedAt: Date | null;
}

export interface LAQuestions {
  correctAnswer: string;
  extraText: string | null;
  imageLinks: Json | null;
  questionId: number;
}

export interface MCQQuestions {
  correctOption: number;
  options: Json;
  questionId: number;
}

export interface PracticeTests {
  difficulty: string;
  numberOfOptions: number;
  numberOfQuestions: number;
  outlines: Json;
  tags: Json;
  testId: string;
}

export interface Questions {
  id: Generated<number>;
  points: number;
  TestId: string | null;
  text: string;
  type: "LONG_ANSWER" | "MCQ";
}

export interface Templates {
  createdAt: Date | null;
  description: string;
  difficulty: string;
  id: string;
  language: string;
  minutesToAnswer: number;
  name: string;
  numberOfOptions: number;
  numberOfQuestions: number;
  outlines: Json;
  tags: Json;
  title: string;
  updatedAt: Date | null;
  userId: string;
}

export interface Tests {
  authorId: string;
  createdAt: Date | null;
  description: string;
  id: string;
  language: Generated<string>;
  minutesToAnswer: number;
  mode: "EXAM" | "PRACTICE";
  title: string;
  updatedAt: Date | null;
}

export interface DB {
  Attempts: Attempts;
  AttemptsAnswerLAQuestions: AttemptsAnswerLAQuestions;
  AttemptsAnswerMCQQuestions: AttemptsAnswerMCQQuestions;
  AttemptsAnswerQuestions: AttemptsAnswerQuestions;
  ExamParticipants: ExamParticipants;
  ExamTests: ExamTests;
  Feedbacks: Feedbacks;
  LAQuestions: LAQuestions;
  MCQQuestions: MCQQuestions;
  PracticeTests: PracticeTests;
  Questions: Questions;
  Templates: Templates;
  Tests: Tests;
}
