openapi: "3.0.3"
info:
  title: SkillSharp Thresh API
  description: API for SkillSharp Thresh
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
